# Site settings
title: Ashish Gandhi
email: ashish.d.gandhi@gmail.com
url: http://ashishgandhi.me/
description: "RPA Develoepr <br> Full-Stack Web Application Developer"
meta_author: Ashish Gandhi

# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Contact form:
# - static : pass through formspree.io to validate email sending
# - disqus : replace contact form by disqus thread
# - comment the line below if you want to stick with the default PHP contact form
contact: static

# If you use disqus you need disqus shortname
# https://help.disqus.com/customer/portal/articles/466208
disqus_shortname: ashishgandhi

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 101010 #80B3FF
  primary-rgb: "255,0,0" #"128,179,255"
  secondary-light: 7a7c71 #FD6E8A
  secondary: 5a5c51 #FD6E8A
  secondary-dark: 363730 #A2122F
  blog-text: 222
  link: 1a77bd

# Blog settings
blog:
  labels:
    modal-close: Close

# Portfolio settings
portfolio:
  labels:
    client: Client
    project-date: Date
    application: Application
    languages: Languages
    concepts: Concepts
    tools: Tools
    stack: Stack
    modal-close: Close

# Footer settings
footer:
  location-header: Location
  location: Tampa, FL
  copyright: Ashish Gandhi. All Rights Reserved.
  social: My Other Whereabouts
  new-thoughts: New Thoughts

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc. search them in main.css)
social:
  - title: github
    url: https://github.com/gandhiashish
  - title: linkedin
    url: https://www.linkedin.com/in/ashish-gandhi-3416b07/
#  - title: codeschool
#    url: https://www.codeschool.com/users/90602
#  - title: laracasts
#    url: https://laracasts.com/@wcmarti2 
#  - title: stack-overflow
#    url: http://stackoverflow.com/users/5743565/bill-martin
#   - title: facebook
#     url: https://www.facebook.com/ashishdgandhi
  - title: rss
    url: /feed.xml


# Credits content
credits: '<a href="https://github.com/gandhiashish/gandhiashish.github.io.git">Fork my portfolio on github</a>'

# Build settings
permalink: pretty

# Markdown/syntax highlighter settings
highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge
